
# Exercise 1

```{r}
base  = ggplot(df.C, aes(x = reorder(Crime, Percent), y = Percent )) 

lolliplot9 = base + geom_segment(stat = 'identity',
                                 aes(inherit.aes=TRUE,
                                     y=0,
                                   xend = Crime,
                                   yend = Percent))
                                 

lolliplot10 = lolliplot9 + facet_wrap( ~ Daytime ,nrow = 1) 

lolliplot11 = lolliplot10 + theme(axis.text.y = element_text(size=4,angle = 45),
                  plot.margin=unit(c(0,1,1,.2),"cm"),
                  text=element_text(color='gray25'),
                  plot.title=element_text(hjust=.3,
                                          size=17,
                                          color='black',
                                          margin=unit(c(.6,0,1,0),'cm')),
                  plot.caption=element_text(size=8,
                                            hjust=1,
                                            margin=unit(c(.25,0,0,0),'cm'))) 

lolliplot11 = lolliplot11 + coord_flip() + geom_point()

lolliplot12 = lolliplot11 + labs(title='Higher variety of crimes occur at night in Seattle',
                                 y='Proportion of total reported crimes by time of day',
                                 x=NULL,
                                 caption='Source: Seattle Police Department')

lolliplot12
```



# Exercise 2
```{r}

base  = ggplot(df.C, aes(x = Daytime, y = reorder(Crime, -Percent), fill = Percent)) 
heat1 = base +  geom_tile() 
heat2 = heat1 +scale_fill_gradient(low = "gold2", 
                                   high = "darkorchid4")

heat3 = heat2 + theme_classic() 

heat4 = heat3 + theme(axis.text.x = element_text(vjust = 0.7),
                      axis.text.y=element_text(size=6),
                      text=element_text(color='gray25'),
                      plot.title=element_text(size=19,
                                              hjust=.6,
                                              color='black',
                                              margin=unit(c(.75,0,.75,0),'cm')),
                      legend.position="right", 
                      legend.direction="vertical",
                      legend.key.width=unit(.75, "cm"),
                      legend.key.height=unit(.75, "cm"),
                      plot.caption=element_text(size=8,
                                            hjust=1.25,
                                            margin=unit(c(.25,0,0,0),'cm')))

heat4 + labs(title='Burglary, car prowl, and theft most common \ncrimes througout the day in Seattle',
               x="Time of Day",
             y=NULL,
             caption='Source: Seattle Police Department')
```


# Exercise 3

```{r}
base= ggplot(crimeYearGG,
             aes(x = reorder(crimecat, YearsToReport, FUN = max), # reorder!
                 y=YearsToReport)) 
mins = base + stat_summary(fun.y=min,size=1,
                           geom="line", linetype='dashed',show.legend = T,
                           aes(group=1,col='Minimum'))
minsMaxs= mins + stat_summary(fun.y=max,
                              geom="line",size=1,show.legend = F,
                              aes(group=1,col='Maximum'))
minsMaxsMd= minsMaxs + stat_summary(fun.y=median, size=2,
                                    geom="line",
                                    aes(group=1,col='Median'))
all3=minsMaxsMd + scale_colour_manual(name="Trends",
                                      values=c("blue", "black","red"))

all4=all3 + labs(title="Reporting times vary by crime type in Seattle",
                 x=NULL,
                 y="Years taken to report crime",
                 caption='Source: Seattle Police Department')

all5=all4 + theme(axis.line=element_line(color='black'),
                  axis.text.y=element_text(size=7),
                  plot.margin=unit(c(0,.25,.5,.25),"cm"),
                  panel.background=element_rect(fill='white'),
                  panel.grid=element_line(color='gray80'),
                   text=element_text(color='gray25'),
                  plot.title=element_text(hjust=1,
                                          size=18,
                                          color='black',
                                          margin=unit(c(.6,0,1,0),'cm')),
                  plot.caption=element_text(size=8,
                                            hjust=1.25,
                                            margin=unit(c(.25,0,0,0),'cm')))

all5 + coord_flip()
```

```{r}
base = ggplot(num_num, aes(daysByNeigh,crimesByNeigh)) 
scatp1 = base +  stat_density_2d(aes(fill = ..density..), 
                                 geom = "raster", contour = FALSE)
scatp2=scatp1+geom_text_repel(aes(label=ifelse(crimesByNeigh>=5,
                                               num_num$rowname, "")))
scatp3 = scatp2 +  theme(legend.position='none') 
scatp4= scatp3 + scale_fill_distiller(palette="Greys", direction=1)
scatp5 = scatp4 +  scale_x_continuous(expand = c(0, 0)) + 
         scale_y_continuous(expand = c(0, 0)) 
scatp6 = scatp5 + labs(title="Four neighborhoods with highest crime rates report faster than average",
                       y='Share of crime (%)',
                       x='Average days to report crime',
                       caption='Source: Seattle Police Department')
scatp7 = scatp6 + theme(plot.title=element_text(hjust=.6,
                                          size=15,
                                          face='bold',
                                          color='black',
                                          margin=unit(c(.25,0,1,0),'cm')),
                        plot.margin=unit(c(0,1,.3,.3),"cm"),
                        panel.background = element_rect(color='black'),
                        axis.line=element_line(color='black'),
                        text=element_text(color='gray25'),
                        plot.caption=element_text(size=8,
                                            hjust=1,
                                            margin=unit(c(.25,0,0,0),'cm')))

scatp7
```

